### DISCUSSION TITLE
Audit Log Collector for PRTG use

### DISCUSSION THREAD

**Discussion by SWA84** [ddbnl/office365-audit-log-collector#35] [Q&A]
Hello,

I created the Azure App for die Audit Log and the sensor for PRTG.
If i start the sensor I get following error:

XML: Das zurückgelieferte XML entspricht nicht dem erwarteten Schema. (Code: PE233) -- JSON: Das zurückgelieferte JSON entspricht nicht der erwarteten Struktur (Invalid JSON.). (Code: PE231)

XML: The returned XML does not conform to the expected schema. (Code: PE233) -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (Code: PE231)

Following is done like in the description:

Make sure Auditing is turned on for your tenant!
Use these instructions: https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?view=o365-worldwide
If you had to turn it on, it may take a few hours to process
Create App registration:
Azure AD > 'App registrations' > 'New registration':
Choose any name for the registration
Choose "Accounts in this organizational directory only (xyz only - Single tenant)"
Hit 'register'
Save 'Tenant ID' and 'Application (Client) ID' from the overview page of the new registration, you will need it to run the collector
Create app secret:
Azure AD > 'App registrations' > Click your new app registration > 'Certificates and secrets' > 'New client secret':
Choose any name and expire date and hit 'add'
Actual key is only shown once upon creation, store it somewhere safe. You will need it to run the collector.
Grant your new app registration 'application' permissions to read the Office API's:
Azure AD > 'App registrations' > Click your new app registration > 'API permissions' > 'Add permissions' > 'Office 365 Management APIs' > 'Application permissions':
Check 'ActivityFeed.Read'
Check 'ActivityFeed.ReadDlp'
Hit 'Add permissions'

But where I have to do following:
Subscribe to audit log feeds of your choice
Set 'autoSubscribe: True' in YAML config file to automate this.
OR Use the '--interactive-subscriber' parameter when executing the collector to manually subscribe to the audit API's of your choice

Its necessery to running the collector if I use it only for PRTG?

In PRTG I did following:

optional) Creating a PRTG sensor
To run with PRTG you must create a sensor:

Copy the OfficeAuditLogCollector.exe executable to the "\Custom Sensors\EXE" sub folder of your PRTG installation

Create a device in PRTG with any host name (e.g. "Office Audit Logs")

Create a 'EXE/Script Advanced Sensor' on that device and choose the executable you just copied

Enter parameters, e.g.: "tenant_id client_key secret_key --config full/path/to/config.yaml" (use full path, because PRTG will execute the script from a different working directory) I used the local path from the PRTG probe... correct?

Copy the prtg.config from ConfigExamples and modify at least the channel names and filters for your needs. (I used the prtg example file)

Set the timeout of the script to something generous that suits the amount of logs you will retrieve. Probably at least 300 seconds. Run the script manually first to check how long it takes.

Match the interval of the sensor to the amount of hours of logs to retrieve. If your interval is 1 hour, hoursToCollect in the config file should also be set to one hour.

I tried also to run the officeAuditLogCollector-V2.3.exe with cmd (admin rights) with 
that path

C:\Skripte\officeAuditLogCollector-V2.3.exe xxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxx xxxxxxxx-xxxx-xxxxx-xxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxx --config C:\Skripte\PRTG_365_Audit_Logs.yaml

A collector.log will be created with following text:
Starting run @ 2022-08-22 08:56:12.615785. Content: deque(['Audit.General', 'Audit.AzureActiveDirectory', 'Audit.SharePoint']).

The file is 0KB. After 4 hours the same. Nothing happens?!?

**Comment by ddbnl** [comment]
Heya,

The steps look good, perhaps it is something in the config. Could you paste the content of the config yaml file here? I will try to reproduce the issue.

**Comment by SWA84** [comment]
Hello,

its the default PRTG config file from your examples:

***@***.***


Mit freundlichen Grüßen
Stefan Wachsmuth
staatl. geprüfter IT-Systemelektroniker
IT-Systemingenieur
Bitte senden Sie allgemeine IT-Service-Anfragen immer an ***@***.*** oder nutzen Sie die IT-Service-Hotline: +49 (561) 8792-190.


HERMANNS HTI-Bau GmbH u. Co. KG
Wilhelm-Speck-Str. 17
34125 Kassel
Deutschland

Telefon +49 (561) 8792-189
Mobil +49 (151) 61588137
E-Mail ***@***.*** ***@***.***>
Internet www.hermanns.de
Kontaktieren Sie mich über ***@***.***>

Kommanditgesellschaft HRA 7346 Kassel
pers. haft. Gesellschafterin:
HERMANNS HTI-Bau und Geschäftsführungs GmbH
Amtsgericht Kassel HRB 3468, USt.-Id.-Nr.: DE 113024495
Geschäftsführer: Hans-Ulrich Hujer, Swen Haar

Ein Unternehmen der HERMANNS-Gruppe.

Sofern nicht anders angegeben, ist diese E-Mail und alle Anlagen vertraulich und nur für den Empfänger bestimmt.
Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhaltes, eine Vervielfältigung
oder Weitergabe der E-Mail ausdrücklich untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die empfangene E-Mail.

Sparen Sie pro nicht gedruckter Seite 250 ml Wasser, 5 g CO2, 15 g Holz und 50 Wh Energie.




Von: ddbnl ***@***.***>
Gesendet: Samstag, 27. August 2022 10:24
An: ddbnl/office365-audit-log-collector ***@***.***>
Cc: Wachsmuth, Stefan ***@***.***>; Author ***@***.***>
Betreff: Re: [ddbnl/office365-audit-log-collector] Audit Log Collector for PRTG use (Discussion #35)


Heya,

The steps look good, perhaps it is something in the config. Could you paste the content of the config yaml file here? I will try to reproduce the issue.

**Comment by ddbnl** [comment]
Sorry for the late reply,  life got in the way.

I believe you may indeed not be subscribed to the audit log feeds yet. This is done automatically if the 'autoSubscribe' parameter is set to true. This is something I should have included in the default PRTG example; I will make a new commit to fix that mistake. I will add a new default config for you below, could you let me know if that works for you? The below config also has the log setting "debug: False"; if you still experience issues, please set this to "True" and provide the log so I can debug further. I think it'll work with auto subsribe however.

```YAML
log:  # Log settings. Debug will severely decrease performance
  path: 'collector.log'
  debug: False
collect:
  contentTypes:
    Audit.General: True
    Audit.AzureActiveDirectory: True
    Audit.SharePoint: True
  skipKnownLogs: False  # Take all logs each time to count the number of active filter hits each interval
  resume: False  # Take all logs each time to count the number of active filter hits each interval
  hoursToCollect: 1  # Period over which to alert, e.g. failed AAD logins over the last hour
  autoSubscribe: True
# The PRTG output defines channels which have filters associated to them. The output of the channel will be
# the number of hits on the filter. E.g. filter for failed AAD logins on a "Failed AAD logins" channel.
output:
  prtg:
    enabled: True
    channels:
    - name: Deleted Sharepoint files
      filters:
        Audit.SharePoint:
          Operation: FileDeleted
    - name: Failed Azure AD logins
      filters:
        Audit.AzureActiveDirectory:
          Operation: UserLoginFailed
    - name: Spoof attempts prevented
      filters:
        Audit.General:
          Policy: Spoof
```
