### ISSUE TITLE
azureLogAnalytics Parameter for Secret Missing

### ISSUE THREAD

**Issue by Gill-Bates** [ddbnl/office365-audit-log-collector#71]
What is the Parameter for the Workspace Secret? It's missing in your Config-Template

```
output:
  azureLogAnalytics:
    workspaceId: xxxx
    enabled: True
```

![image](https://github.com/ddbnl/office365-audit-log-collector/assets/25774289/9f28b87b-c6be-45c7-85c4-63e8c3bbb01b)
